### PR TITLE
fix: stop failing baselining when the database is not empty

### PR DESCRIPTION
**Pull request by ununhexium**
```[tasklist]
### Checklist
- [x] The PR title is short and expressive.
- [x] I have updated the CHANGELOG.md. See [changelog_update.md](https://github.com/sovity/authority-portal/tree/main/docs/dev/changelog_updates.md) for more information.
- [ ] I have updated the Deployment Migration Notes Section in the CHANGELOG.md for any configuration / external API changes.
- [ ] I have updated the Community Edition [Postman-Collection](https://github.com/sovity/edc-ce/blob/main/docs/api/postman_collection.json) if I changed existing APIs or added new APIs (e.g. for Management-API or API-Wrapper)
- [x] I have performed a **self-review**
```

### CODE REVIEW

**Review by tmberthold — CHANGES_REQUESTED** [review]
You also need to look at the deployment docs if something needs to be updated e.g. not needing a note on a extra LH DB here
https://github.com/sovity/edc-ce/tree/main/docs/deployment-guide/goals/production

**Comment by ununhexium** [comment]
> You also need to look at the deployment docs if something needs to be updated e.g. not needing a note on a extra LH DB here https://github.com/sovity/edc-ce/tree/main/docs/deployment-guide/goals/production

Do you want to make it the same as the EDC's database+schema by default?

**Comment by tmberthold** [comment]
> > You also need to look at the deployment docs if something needs to be updated e.g. not needing a note on a extra LH DB here https://github.com/sovity/edc-ce/tree/main/docs/deployment-guide/goals/production
> 
> Do you want to make it the same as the EDC's database+schema by default?

If we now use the same DB for EDC and LH, this makes somewhat sense to me. The main thing is that it works.

**Review by richardtreier — APPROVED** [review]
LGTM

**Pull request merged**
